services:
    db: #serviço do banco de dados mysql
      image: mysql:latest #imagem do mysql
      command: mysqld --default-authentication-plugin=mysql_native_password #comando para inicializar o mysql no container
      volumes: #definir os volumes
        - ./db_data:/var/lib/mysql
      environment: #variáveis de ambiente
        TZ: America/Sao_Paulo #timezone
        MYSQL_ROOT_PASSWORD: root #senha do root
        MYSQL_USER: amadeu #usuário
        MYSQL_PASSWORD: amadeu #senha
        MYSQL_DATABASE: wordpress #banco de dados
      ports:
        - 3308:3306 #portas que vão ser expostas
      networks:
        - wordpress-network